version: '3.8'

services:
  portal:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx-modsec-portal
    ports:
      - "8088:8088"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8088/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - NODE_ENV=production
    networks:
      - portal-network

  # Optional mock API server (can be enabled if needed)
  # mockserver:
  #   image: mockserver/mockserver:latest
  #   container_name: portal-mockserver
  #   ports:
  #     - "1080:1080"
  #   environment:
  #     - MOCKSERVER_PROPERTY_FILE=/config/mockserver.properties
  #   networks:
  #     - portal-network

networks:
  portal-network:
    driver: bridge
