import fs from 'fs/promises';
import { exec } from 'child_process';
import { promisify } from 'util';
import logger from '../../../utils/logger';
import { botManagerRepository } from '../bot-manager.repository';
import {
  BotRuleEntity,
  BotNginxResult,
  BotPolicyMode,
  JA4_DIRECTIVE_MAP,
  JA4_ENFORCEABLE_TYPES,
} from '../bot-manager.types';
import { sanitizeProfileName, sanitizeNginxCommentText } from '../utils/fingerprint-validators';

const execAsync = promisify(exec);

export class BotNginxService {
  private readonly GLOBAL_CONF = '/etc/nginx/conf.d/bot-manager-global.conf';
  private readonly PROFILES_DIR = '/etc/nginx/bot-profiles';
  private readonly NGINX_TEST_CMD = 'nginx -t';
  private readonly NGINX_RELOAD_CMD = 'nginx -s reload';

  async generateGlobalConfig(): Promise<string> {
    const rules = await botManagerRepository.findGlobalRules(true);
    return this.buildConfigFile('Global Bot Manager Rules', rules, null);
  }

  async generateProfileConfig(profileId: string): Promise<string> {
    const profile = await botManagerRepository.findProfileById(profileId);
    if (!profile) {
      throw new Error('Bot profile not found');
    }

    const rules = profile.rules.filter((r) => r.enabled && r.action !== 'log_only');
    return this.buildConfigFile(`Bot Profile: ${profile.name}`, rules, profile.policyMode);
  }

  private buildConfigFile(
    title: string,
    rules: BotRuleEntity[],
    policyMode: BotPolicyMode | null
  ): string {
    const cleanTitle = sanitizeNginxCommentText(title);
    let config = `# ${cleanTitle} - Auto-generated by Nginx Love UI
# Do not edit manually
# Generated at: ${new Date().toISOString()}

`;

    const activeRules = rules.filter((r) => r.action !== 'log_only');

    for (const type of JA4_ENFORCEABLE_TYPES) {
      const typeRules = activeRules
        .filter((r) => r.fingerprintType === type)
        .sort((a, b) => a.priority - b.priority);

      if (typeRules.length === 0) continue;

      config += `# ===== ${type.toUpperCase()} Rules =====\n\n`;

      const allows = typeRules.filter((r) => r.action === 'allow');
      const denies = typeRules.filter((r) => r.action === 'deny');

      for (const rule of allows) {
        const cleanName = sanitizeNginxCommentText(rule.name);
        config += `# ${cleanName}\n`;
        config += `${JA4_DIRECTIVE_MAP[type].allow} "${this.escapeFingerprint(rule.fingerprint)}";\n`;
      }

      for (const rule of denies) {
        const cleanName = sanitizeNginxCommentText(rule.name);
        config += `# ${cleanName}\n`;
        config += `${JA4_DIRECTIVE_MAP[type].deny} "${this.escapeFingerprint(rule.fingerprint)}";\n`;
      }

      if (policyMode === 'whitelist' && allows.length > 0) {
        config += `# Whitelist mode: deny all other ${type} fingerprints\n`;
        config += `${JA4_DIRECTIVE_MAP[type].deny} "all";\n`;
      }

      config += '\n';
    }

    if (activeRules.length === 0) {
      config += '# No active rules\n';
    }

    return config;
  }

  private escapeFingerprint(fingerprint: string): string {
    return fingerprint.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
  }

  async writeGlobalConfig(config: string): Promise<void> {
    await fs.mkdir('/etc/nginx/conf.d', { recursive: true });
    await fs.writeFile(this.GLOBAL_CONF, config, 'utf8');
    logger.info(`Bot Manager global config written to ${this.GLOBAL_CONF}`);
  }

  async writeProfileConfig(profileName: string, config: string): Promise<void> {
    await fs.mkdir(this.PROFILES_DIR, { recursive: true });
    const safeName = sanitizeProfileName(profileName);
    const filePath = `${this.PROFILES_DIR}/${safeName}.conf`;
    await fs.writeFile(filePath, config, 'utf8');
    logger.info(`Bot profile config written to ${filePath}`);
  }

  async deleteProfileConfig(profileName: string): Promise<void> {
    const safeName = sanitizeProfileName(profileName);
    const filePath = `${this.PROFILES_DIR}/${safeName}.conf`;
    try {
      await fs.unlink(filePath);
    } catch {
      // ignore missing file
    }
  }

  async testNginxConfig(): Promise<boolean> {
    try {
      await execAsync(this.NGINX_TEST_CMD);
      return true;
    } catch (error: unknown) {
      const err = error as { stderr?: string; message?: string };
      logger.error('Nginx config test failed:', err.stderr || err.message);
      return false;
    }
  }

  async reloadNginx(): Promise<void> {
    await execAsync(this.NGINX_RELOAD_CMD);
    logger.info('Nginx reloaded after Bot Manager config update');
  }

  async applyAll(): Promise<BotNginxResult> {
    try {
      logger.info('Applying Bot Manager rules...');

      const globalConfig = await this.generateGlobalConfig();
      await this.writeGlobalConfig(globalConfig);

      const profiles = await botManagerRepository.findAllProfiles({ limit: 1000 });
      for (const profile of profiles.profiles) {
        if (profile.enabled) {
          const profileConfig = await this.generateProfileConfig(profile.id);
          await this.writeProfileConfig(profile.name, profileConfig);
        } else {
          await this.deleteProfileConfig(profile.name);
        }
      }

      const testPassed = await this.testNginxConfig();
      if (!testPassed) {
        return {
          success: false,
          message: 'Nginx configuration test failed. Bot rules not applied.',
        };
      }

      await this.reloadNginx();

      return { success: true, message: 'Bot Manager rules applied successfully' };
    } catch (error: unknown) {
      const err = error as Error;
      logger.error('Failed to apply Bot Manager rules:', err);
      return { success: false, message: `Failed to apply Bot Manager rules: ${err.message}` };
    }
  }

  async applyProfile(profileId: string): Promise<BotNginxResult> {
    try {
      const profile = await botManagerRepository.findProfileById(profileId);
      if (!profile) {
        return { success: false, message: 'Bot profile not found' };
      }

      if (profile.enabled) {
        const config = await this.generateProfileConfig(profileId);
        await this.writeProfileConfig(profile.name, config);
      } else {
        await this.deleteProfileConfig(profile.name);
      }

      const globalConfig = await this.generateGlobalConfig();
      await this.writeGlobalConfig(globalConfig);

      const testPassed = await this.testNginxConfig();
      if (!testPassed) {
        return { success: false, message: 'Nginx configuration test failed.' };
      }

      await this.reloadNginx();
      return { success: true, message: 'Bot profile applied successfully' };
    } catch (error: unknown) {
      const err = error as Error;
      return { success: false, message: err.message };
    }
  }

  async previewAll(): Promise<string> {
    const globalConfig = await this.generateGlobalConfig();
    const profiles = await botManagerRepository.findAllProfiles({ limit: 1000 });
    let preview = globalConfig + '\n\n';

    for (const profile of profiles.profiles) {
      preview += `# --- Profile: ${sanitizeNginxCommentText(profile.name)} ---\n`;
      preview += await this.generateProfileConfig(profile.id);
      preview += '\n\n';
    }

    return preview;
  }
}

export const botNginxService = new BotNginxService();
